//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttributeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAttributeGroup()
        {
            this.tblAttributeGroupDetails = new HashSet<tblAttributeGroupDetail>();
        }
    
        public int ID { get; set; }
        public System.Guid MUID { get; set; }
        public int Entity_ID { get; set; }
        public byte MemberType_ID { get; set; }
        public string Name { get; set; }
        public int SortOrder { get; set; }
        public bool FreezeNameCode { get; set; }
        public bool IsSystem { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public int EnterUserID { get; set; }
        public int EnterVersionID { get; set; }
        public System.DateTime LastChgDTM { get; set; }
        public int LastChgUserID { get; set; }
        public int LastChgVersionID { get; set; }
    
        public virtual tblEntity tblEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttributeGroupDetail> tblAttributeGroupDetails { get; set; }
    }
}
