//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttribute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAttribute()
        {
            this.tblAttribute1 = new HashSet<tblAttribute>();
            this.tblAttribute11 = new HashSet<tblAttribute>();
            this.tblAttributeGroupDetails = new HashSet<tblAttributeGroupDetail>();
            this.tblDerivedHierarchyDetails = new HashSet<tblDerivedHierarchyDetail>();
        }
    
        public int ID { get; set; }
        public System.Guid MUID { get; set; }
        public Nullable<int> Source_ID { get; set; }
        public byte[] Source_LastChgTS { get; set; }
        public int Entity_ID { get; set; }
        public byte MemberType_ID { get; set; }
        public string DisplayName { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string TableColumn { get; set; }
        public byte AttributeType_ID { get; set; }
        public byte DataType_ID { get; set; }
        public Nullable<int> DataTypeInformation { get; set; }
        public int InputMask_ID { get; set; }
        public int DisplayWidth { get; set; }
        public int SortOrder { get; set; }
        public Nullable<int> DomainEntity_ID { get; set; }
        public int ChangeTrackingGroup { get; set; }
        public Nullable<int> FilterParentAttribute_ID { get; set; }
        public Nullable<int> FilterHierarchyDetail_ID { get; set; }
        public bool IsCode { get; set; }
        public bool IsName { get; set; }
        public bool IsSystem { get; set; }
        public bool IsReadOnly { get; set; }
        public bool IsRequired { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public int EnterUserID { get; set; }
        public int EnterVersionID { get; set; }
        public System.DateTime LastChgDTM { get; set; }
        public int LastChgUserID { get; set; }
        public int LastChgVersionID { get; set; }
        public byte[] LastChgTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttribute> tblAttribute1 { get; set; }
        public virtual tblAttribute tblAttribute2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttribute> tblAttribute11 { get; set; }
        public virtual tblAttribute tblAttribute3 { get; set; }
        public virtual tblDerivedHierarchyDetail tblDerivedHierarchyDetail { get; set; }
        public virtual tblEntity tblEntity { get; set; }
        public virtual tblEntity tblEntity1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttributeGroupDetail> tblAttributeGroupDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDerivedHierarchyDetail> tblDerivedHierarchyDetails { get; set; }
    }
}
