//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBRItemTypeAppliesTo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBRItemTypeAppliesTo()
        {
            this.tblBRItems = new HashSet<tblBRItem>();
        }
    
        public int ID { get; set; }
        public int BRItemType_ID { get; set; }
        public int ApplyTo_ID { get; set; }
        public Nullable<int> Sequence { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBRItem> tblBRItems { get; set; }
        public virtual tblListRelationship tblListRelationship { get; set; }
    }
}
