//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBRItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBRItem()
        {
            this.tblBRItemProperties = new HashSet<tblBRItemProperty>();
        }
    
        public int ID { get; set; }
        public int BRLogicalOperatorGroup_ID { get; set; }
        public int BRItemAppliesTo_ID { get; set; }
        public int Sequence { get; set; }
        public string ItemText { get; set; }
        public string AnchorName { get; set; }
        public Nullable<int> AnchorAttributeType { get; set; }
        public System.Guid MUID { get; set; }
    
        public virtual tblBRItemTypeAppliesTo tblBRItemTypeAppliesTo { get; set; }
        public virtual tblBRLogicalOperatorGroup tblBRLogicalOperatorGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBRItemProperty> tblBRItemProperties { get; set; }
    }
}
