//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBRLogicalOperatorGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblBRLogicalOperatorGroup()
        {
            this.tblBRItems = new HashSet<tblBRItem>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LogicalOperator_ID { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public int BusinessRule_ID { get; set; }
        public int Sequence { get; set; }
        public System.Guid MUID { get; set; }
    
        public virtual tblBRBusinessRule tblBRBusinessRule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBRItem> tblBRItems { get; set; }
    }
}
