//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCodeGenInfo
    {
        public int EntityId { get; set; }
        public int Seed { get; set; }
        public Nullable<long> LargestCodeValue { get; set; }
    
        public virtual tblEntity tblEntity { get; set; }
    }
}
