//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDBUpgradeHistory
    {
        public int ID { get; set; }
        public int DBVersion { get; set; }
        public string EnterUser { get; set; }
        public System.DateTime EnterDTM { get; set; }
    }
}
