//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDerivedHierarchyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDerivedHierarchyDetail()
        {
            this.tblAttributes = new HashSet<tblAttribute>();
        }
    
        public int ID { get; set; }
        public System.Guid MUID { get; set; }
        public int DerivedHierarchy_ID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public Nullable<int> ForeignParent_ID { get; set; }
        public Nullable<int> Foreign_ID { get; set; }
        public byte ForeignType_ID { get; set; }
        public Nullable<int> ManyToManyChildAttribute_ID { get; set; }
        public Nullable<int> Level_ID { get; set; }
        public bool IsVisible { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public int EnterUserID { get; set; }
        public int EnterVersionID { get; set; }
        public System.DateTime LastChgDTM { get; set; }
        public int LastChgUserID { get; set; }
        public int LastChgVersionID { get; set; }
        public byte[] LastChgTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttribute> tblAttributes { get; set; }
        public virtual tblAttribute tblAttribute { get; set; }
        public virtual tblDerivedHierarchy tblDerivedHierarchy { get; set; }
    }
}
