//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public int ID { get; set; }
        public System.Guid MUID { get; set; }
        public Nullable<int> Version_ID { get; set; }
        public Nullable<int> Entity_ID { get; set; }
        public string EventName { get; set; }
        public byte EventStatus_ID { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public int EnterUserID { get; set; }
        public System.DateTime LastChgDTM { get; set; }
        public int LastChgUserID { get; set; }
        public string ErrorMsg { get; set; }
    
        public virtual tblEntity tblEntity { get; set; }
        public virtual tblModelVersion tblModelVersion { get; set; }
    }
}
