//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblList
    {
        public int ID { get; set; }
        public string ListCode { get; set; }
        public string ListName { get; set; }
        public int Seq { get; set; }
        public string ListOption { get; set; }
        public int OptionID { get; set; }
        public bool IsVisible { get; set; }
        public int Group_ID { get; set; }
    }
}
