//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblListRelationship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblListRelationship()
        {
            this.tblBRItemTypeAppliesToes = new HashSet<tblBRItemTypeAppliesTo>();
        }
    
        public int ID { get; set; }
        public string ParentListCode { get; set; }
        public int Parent_ID { get; set; }
        public string ChildListCode { get; set; }
        public int Child_ID { get; set; }
        public int ListRelationshipType_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblBRItemTypeAppliesTo> tblBRItemTypeAppliesToes { get; set; }
        public virtual tblListRelationshipType tblListRelationshipType { get; set; }
    }
}
