//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStgErrorDetail
    {
        public int ID { get; set; }
        public int Batch_ID { get; set; }
        public string Code { get; set; }
        public string AttributeName { get; set; }
        public string AttributeValue { get; set; }
        public int UniqueErrorCode { get; set; }
    }
}
