//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStgBatch
    {
        public int ID { get; set; }
        public Nullable<int> OriginalBatch_ID { get; set; }
        public System.Guid MUID { get; set; }
        public Nullable<int> Entity_ID { get; set; }
        public Nullable<byte> MemberType_ID { get; set; }
        public string BatchTag { get; set; }
        public Nullable<int> ExternalSystem_ID { get; set; }
        public string Name { get; set; }
        public int Version_ID { get; set; }
        public Nullable<int> TotalMemberCount { get; set; }
        public Nullable<int> ErrorMemberCount { get; set; }
        public Nullable<int> TotalMemberAttributeCount { get; set; }
        public Nullable<int> ErrorMemberAttributeCount { get; set; }
        public Nullable<int> TotalMemberRelationshipCount { get; set; }
        public Nullable<int> ErrorMemberRelationshipCount { get; set; }
        public byte Status_ID { get; set; }
        public Nullable<System.DateTime> LastRunStartDTM { get; set; }
        public Nullable<int> LastRunStartUserID { get; set; }
        public Nullable<System.DateTime> LastRunEndDTM { get; set; }
        public Nullable<int> LastRunEndUserID { get; set; }
        public Nullable<System.DateTime> LastClearedDTM { get; set; }
        public Nullable<int> LastClearedUserID { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public int EnterUserID { get; set; }
    
        public virtual tblEntity tblEntity { get; set; }
    }
}
