//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSecurityPrivilegeFunctional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSecurityPrivilegeFunctional()
        {
            this.tblSecurityRoleAccessFunctionals = new HashSet<tblSecurityRoleAccessFunctional>();
        }
    
        public byte ID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSecurityRoleAccessFunctional> tblSecurityRoleAccessFunctionals { get; set; }
    }
}
