//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSyncRelationship
    {
        public int ID { get; set; }
        public int SourceVersion_ID { get; set; }
        public int SourceEntity_ID { get; set; }
        public int TargetVersion_ID { get; set; }
        public int TargetEntity_ID { get; set; }
        public bool TargetEntityNameIsAliased { get; set; }
        public Nullable<int> RefreshFrequencyInHours { get; set; }
        public Nullable<System.DateTime> LastSuccessfulSyncDTM { get; set; }
        public byte[] LastSuccessfulSyncTimestamp { get; set; }
        public Nullable<System.DateTime> LastSyncAttemptDTM { get; set; }
        public byte LastSyncAttemptStatus { get; set; }
        public string LastSyncAttemptErrorInfo { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public int EnterUserID { get; set; }
        public System.DateTime LastChgDTM { get; set; }
        public int LastChgUserID { get; set; }
        public byte[] LastChgTS { get; set; }
    
        public virtual tblEntity tblEntity { get; set; }
        public virtual tblEntity tblEntity1 { get; set; }
        public virtual tblModelVersion tblModelVersion { get; set; }
        public virtual tblModelVersion tblModelVersion1 { get; set; }
    }
}
