//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S1G6_SISAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSystem
    {
        public int ID { get; set; }
        public string SchemaVersion { get; set; }
        public System.DateTime EnterDTM { get; set; }
        public string EnterUserID { get; set; }
        public string LastChgUserID { get; set; }
        public System.DateTime LastChgDTM { get; set; }
    }
}
